"""
Create data.yaml configuration file for Ultralytics training.

Generates YAML configuration file for YOLO models (YOLOv5, YOLOv11, etc.)
following Ultralytics dataset structure.
"""

from pathlib import Path


def create_data_yaml(output_dir: Path):
    """
    Create data.yaml configuration file for Ultralytics training.

    Args:
        output_dir: Dataset root directory
    """
    # Create YAML content with relative paths
    yaml_content = f"""# Auto-generated by dataset creation script
# Following Ultralytics dataset structure: https://docs.ultralytics.com/datasets/

path: {output_dir}
train: images/train
val: images/val
# Number of classes
nc: 1

# Class names
names:
  0: car
"""

    # Write to data.yaml
    yaml_path = output_dir / "data.yaml"
    with open(yaml_path, "w") as f:
        f.write(yaml_content)

    print(f"\nCreated data.yaml: {yaml_path}")

