EXEC:
  DATASETS:
    # - caldot1-y11
    # - caldot2-y11
    - caldot1-y05
    - caldot2-y05
    - jnc0
    - jnc2
    - jnc6
    - jnc7
    # - caldot1
    # - caldot2
    # - ams
    - ams-y05
    # - ams-y11
  VIDEO_SETS:
    - valid
    - test
  CLASSIFIERS:
    # - YoloN
    - ShuffleNet05
    # - MobileNetS
    # - Perfect
  TILE_SIZES:
    - 60
  TILEPADDING_MODES:
    - none
    - plus
    # - tl
    - tr
    - bl
    # - br
    - square
  CANVAS_SCALE:
    - 1
    - 1.25
    # - 1.5
  TRACKERS:
    # - sortcython
    - ocsortcython
    - bytetrackcython
  SAMPLE_RATES:
    - 1
    - 2
    - 4
    - 8
    # - 16
  TRACKING_ACCURACY_THRESHOLDS:
    - null    # No pruning, skip p022
    - 0.4
    - 0.6
    # - 0.7
    - 0.8

DATA:
  SOURCE_DIR: /polyis-data/sources
  DATASETS_DIR: /polyis-data/datasets
  CACHE_DIR: /polyis-cache/
  EXCLUDE_AREA:
    ams: /polyis/data/exclude/ams.xml
  OTIF_DATASET: /otif-dataset/dataset

OPS:
  preprocess_dataset:
    batch_size: 128
    segment_size: 60
    num_segments: 18

  classify:
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]

SETTINGS:
  GPU_WARMUP: true
