#!/usr/local/bin/python

import argparse
import itertools
import json
import os
import shutil
import time
import cv2
import torch.multiprocessing as mp
import queue
import threading
from functools import partial
from typing import Callable
import numpy as np
import torch

import polyis.models.detector
import polyis.dtypes
from polyis.utilities import TilePadding, format_time, ProgressBar, get_config, build_param_str
from polyis.io import cache, store
from polyis.pareto import build_pareto_combo_filter


config = get_config()
CLASSIFIERS: list[str] = config['EXEC']['CLASSIFIERS']
TILE_SIZES: list[int] = config['EXEC']['TILE_SIZES']
DATASETS: list[str] = config['EXEC']['DATASETS']
SAMPLE_RATES: list[int] = config['EXEC']['SAMPLE_RATES']
TILEPADDING_MODES: list[TilePadding] = config['EXEC']['TILEPADDING_MODES']
CANVAS_SCALES: list[float] = config['EXEC']['CANVAS_SCALE']
TRACKERS: list[str] = config['EXEC']['TRACKERS']
TRACKING_ACCURACY_THRESHOLDS: list[float] = config['EXEC']['TRACKING_ACCURACY_THRESHOLDS']


def parse_args():
    parser = argparse.ArgumentParser(description='Detect objects from packed images generated by 030_exec_pack.py')
    parser.add_argument('--clear', action='store_true',
                        help='Remove and recreate the 040_compressed_detections folder for each video')
    parser.add_argument('--batch_size', type=int, default=4,
                        help='Batch size for detection processing (default: 4)')
    parser.add_argument('--test', action='store_true')
    parser.add_argument('--valid', action='store_true')
    return parser.parse_args()


def detect_worker_thread(dataset: str, batch_queue: queue.Queue, result_queue: queue.Queue,
                         len_images: int, batch_size: int, gpu_id: int, stream: torch.cuda.Stream):
    """
    Worker thread for detecting objects in compressed images using auto-selected detector with CUDA streams.

    Each thread uses its own CUDA stream to enable true parallel execution on the GPU.
    The stream ensures that operations from different threads don't block each other.
    All GPU operations (data transfer and inference) happen within the stream context,
    and data transfers use non_blocking=True to allow overlap with computation.

    Args:
        dataset (str): Name of the dataset (used to auto-select detector)
        batch_queue (queue.Queue): Queue containing batches of images to process (batch_start, batch_images)
        result_queue (queue.Queue): Queue to send results back (batch_start, batch_end, detections)
        len_images (int): Total number of images to detect
        batch_size (int): Batch size for detection processing
        gpu_id (int): GPU ID to use for processing
        stream (torch.cuda.Stream): CUDA stream for this thread's operations
    """
    # Set the current device for this thread
    torch.cuda.set_device(gpu_id)

    # Get detector instance for this thread
    detector = polyis.models.detector.get_detector(dataset, gpu_id, batch_size, len_images)

    with torch.no_grad(), torch.inference_mode():
        # Process images in batches
        while True:
            batch_data = batch_queue.get(block=True)
            if batch_data is None:
                break

            batch_start, batch_images = batch_data
            batch_end = min(batch_start + len(batch_images), len_images)

            # Run detection within the stream context for true parallelism
            # All PyTorch operations (including data transfers and model inference) will
            # be queued to this specific stream, allowing parallel execution with other streams
            with torch.cuda.stream(stream):
                # Run detection on the batch of images (already numpy arrays)
                # The detect_batch function will handle device placement, and since we're
                # in a stream context, PyTorch operations will use this stream
                batch_output = polyis.models.detector.detect_batch(batch_images, detector)

            # Send results back to main thread
            result_queue.put((batch_start, batch_end, batch_output))


def detect_parallel(dataset: str, video: str, classifier: str, tilesize: int,
                    sample_rate: int, tilepadding: TilePadding, canvas_scale: float,
                    tracker: str | None, tracking_accuracy_threshold: float | None,
                    batch_size: int, gpu_id: int):
    """
    Detect objects in compressed images using auto-selected detector with CUDA streams for true parallelism.

    Uses threading with CUDA streams to enable parallel execution of multiple detection operations
    on the same GPU without blocking each other.

    Args:
        dataset_name (str): Name of the dataset (used to auto-select detector)
        video (str): Name of the video file
        classifier (str): Classifier name used for compression
        tilesize (int): Tile size used for compression
        tilepadding (TilePadding): Whether padding was applied to classification results
        sample_rate (int): Sample rate for frame sampling
        canvas_scale (float): Canvas scale used for compression outputs
        tracker (str): Tracker name for upstream pruning
        tracking_accuracy_threshold (float | None): Accuracy threshold for pruning (None = no pruning)
        gpu_id (int): GPU ID to use for processing
    """
    # Enable cuDNN benchmarking for optimal performance
    torch.backends.cudnn.benchmark = True

    param_str = build_param_str(classifier=classifier, tilesize=tilesize, sample_rate=sample_rate, tilepadding=tilepadding, canvas_scale=canvas_scale, tracker=tracker, tracking_accuracy_threshold=tracking_accuracy_threshold)

    compressed_frames_dir = cache.exec(dataset, 'comp-frames', video, param_str, 'images')
    assert os.path.exists(compressed_frames_dir), \
        f"Compressed frames directory {compressed_frames_dir} does not exist"

    # Create output directory for detections
    print(f"Creating output directory for detections")
    detections_output_dir = cache.exec(dataset, 'comp-dets', video, param_str)
    if os.path.exists(detections_output_dir):
        # Remove the entire directory
        shutil.rmtree(detections_output_dir)
    os.makedirs(detections_output_dir, exist_ok=True)

    # Get all compressed image files
    image_files = [f for f in os.listdir(compressed_frames_dir) if f.endswith('.jpg')]
    image_files.sort()  # Ensure consistent ordering
    print(f"Found {len(image_files)} image files")

    # Read all images in the main thread to avoid I/O overhead in worker threads
    print(f"Reading {len(image_files)} frames")
    frames: list[np.ndarray] = []
    for image_file in image_files:
        image_path = os.path.join(compressed_frames_dir, image_file)
        frame = cv2.imread(image_path)
        assert frame is not None
        assert polyis.dtypes.is_np_image(frame)
        frames.append(frame)
    print(f"Read {len(frames)} frames")

    num_threads = 2
    with (open(os.path.join(detections_output_dir, 'detections.jsonl'), 'w') as f,
          open(os.path.join(detections_output_dir, 'runtimes.jsonl'), 'w') as fr):
        # Use thread-safe queues for inter-thread communication
        batch_queue = queue.Queue()
        result_queue = queue.Queue()

        # Set device for main thread
        torch.cuda.set_device(gpu_id)

        # Create unique CUDA streams for each worker thread
        # Each stream allows independent parallel execution on the GPU
        streams = [torch.cuda.Stream(device=gpu_id) for _ in range(num_threads)]

        # Start worker threads
        # Each thread uses its own CUDA stream to enable true parallelism
        threads = []
        print(f"Starting {num_threads} threads with CUDA streams for parallel GPU execution")
        for i in range(num_threads):
            thread = threading.Thread(target=detect_worker_thread,
                                       args=(dataset, batch_queue, result_queue,
                                             len(image_files), batch_size, gpu_id, streams[i]))
            threads.append(thread)
            thread.start()

        # Queue all batches with images for processing
        num_batches = (len(image_files) + batch_size - 1) // batch_size
        print(f"Queuing {num_batches} batches for processing")
        start_time = (time.time_ns() / 1e6)

        for i in range(num_batches):
            batch_start = i * batch_size
            batch_end = min(batch_start + batch_size, len(image_files))
            batch_images = frames[batch_start:batch_end]
            # Pass batch of numpy arrays through queue
            batch_queue.put((batch_start, batch_images))

        # Signal threads to stop by sending None for each thread
        for i in range(num_threads):
            batch_queue.put(None)

        # Collect results from all threads
        # Results may arrive out of order, so we collect them all first
        results_dict: dict[int, polyis.dtypes.DetArray] = {}
        completed_batches = 0
        while completed_batches < num_batches:
            result_data = result_queue.get(block=True)
            batch_start, batch_end, batch_output = result_data
            # Store results by batch start index
            for i, detection in enumerate(batch_output):
                results_dict[batch_start + i] = detection
            completed_batches += 1

        # Wait for all threads to finish
        for thread in threads:
            thread.join()

        # Synchronize all streams to ensure all GPU work is complete
        for stream in streams:
            stream.synchronize()
        torch.cuda.synchronize()
        end_time = (time.time_ns() / 1e6)

        # Write results in order
        for i in range(len(image_files)):
            output_detection = results_dict[i]
            assert output_detection is not None
            f.write(json.dumps({ 'image_file': image_files[i], 'bboxes': output_detection.tolist() }) + '\n')
            fr.write(json.dumps(format_time(detect=(end_time - start_time) / len(image_files))) + '\n')


def detect_objects(dataset: str, video: str, classifier: str, tilesize: int,
                   sample_rate: int, tilepadding: TilePadding, canvas_scale: float,
                   tracker: str | None, tracking_accuracy_threshold: float | None,
                   batch_size: int, detector):
    """
    Detect objects in compressed images using a pre-initialized detector.

    Args:
        dataset_name (str): Name of the dataset (used to auto-select detector)
        video (str): Name of the video file
        classifier (str): Classifier name used for compression
        tilesize (int): Tile size used for compression
        tilepadding (TilePadding): Whether padding was applied to classification results
        sample_rate (int): Sample rate for frame sampling
        canvas_scale (float): Canvas scale used for compression outputs
        tracker (str): Tracker name for upstream pruning
        tracking_accuracy_threshold (float | None): Accuracy threshold for pruning (None = no pruning)
        detector: Pre-initialized detector instance shared across all videos in this parameter combo
    """
    param_str = build_param_str(classifier=classifier, tilesize=tilesize, sample_rate=sample_rate, tilepadding=tilepadding, canvas_scale=canvas_scale, tracker=tracker, tracking_accuracy_threshold=tracking_accuracy_threshold)

    compressed_frames_dir = cache.exec(dataset, 'comp-frames', video, param_str, 'images')
    assert os.path.exists(compressed_frames_dir), \
        f"Compressed frames directory {compressed_frames_dir} does not exist"

    # Create output directory for detections
    detections_output_dir = cache.exec(dataset, 'comp-dets', video, param_str)
    if os.path.exists(detections_output_dir):
        # Remove the entire directory
        shutil.rmtree(detections_output_dir)
    os.makedirs(detections_output_dir, exist_ok=True)

    # Get all compressed image files
    image_files = [f for f in os.listdir(compressed_frames_dir) if f.endswith('.jpg')]

    with (open(os.path.join(detections_output_dir, 'detections.jsonl'), 'w') as f,
          open(os.path.join(detections_output_dir, 'runtimes.jsonl'), 'w') as fr,
          torch.no_grad()):
        # Process images in batches
        for batch_start in range(0, len(image_files), batch_size):
            batch_end = min(batch_start + batch_size, len(image_files))
            batch_files = image_files[batch_start:batch_end]

            # Read all images in the batch
            batch_images: list[polyis.dtypes.NPImage] = []
            batch_runtimes: list[dict] = []
            start_time = (time.time_ns() / 1e6)
            for image_file in batch_files:
                image_path = os.path.join(compressed_frames_dir, image_file)
                frame = cv2.imread(image_path)
                assert frame is not None
                assert polyis.dtypes.is_np_image(frame)
                batch_images.append(frame)
                batch_runtimes.append({'image_file': image_file})
            end_time = (time.time_ns() / 1e6)
            read_time_per_image = (end_time - start_time) / len(batch_files)

            # Detect objects in the batch
            start_time = (time.time_ns() / 1e6)
            batch_outputs = polyis.models.detector.detect_batch(batch_images, detector)
            end_time = (time.time_ns() / 1e6)
            detect_time_per_image = (end_time - start_time) / len(batch_files)

            # Process results for each image in the batch
            for idx, (image_file, outputs) in enumerate(zip(batch_files, batch_outputs)):
                runtime = batch_runtimes[idx]
                runtime['read'] = read_time_per_image
                runtime['detect'] = detect_time_per_image

                # Extract bounding boxes (x1, y1, x2, y2, score, ...) format
                bounding_boxes = outputs.tolist()

                # Save detection results
                f.write(json.dumps({ 'image_file': image_file, 'bboxes': bounding_boxes }) + '\n')
                fr.write(json.dumps(format_time(**runtime)) + '\n')


def detect_all(dataset: str, videos: list[str], classifier: str, tilesize: int,
               sample_rate: int, tilepadding: TilePadding, canvas_scale: float,
               tracker: str | None, tracking_accuracy_threshold: float | None,
               batch_size: int, gpu_id: int, command_queue: mp.Queue):
    device = f'cuda:{gpu_id}'
    # Build a human-readable description for the progress bar.
    param_str = build_param_str(classifier=classifier, tilesize=tilesize, sample_rate=sample_rate,
                                tilepadding=tilepadding, canvas_scale=canvas_scale, tracker=tracker,
                                tracking_accuracy_threshold=tracking_accuracy_threshold)
    description = f"{dataset} {param_str}"

    # Initialize the detector once for all videos in this parameter combination.
    # Use the first video's image count as a representative batch-size hint.
    first_compressed_frames_dir = cache.exec(dataset, 'comp-frames', videos[0], param_str, 'images')
    first_image_files = sorted(f for f in os.listdir(first_compressed_frames_dir) if f.endswith('.jpg'))
    detector = polyis.models.detector.get_detector(dataset, gpu_id, batch_size, len(first_image_files))

    # Warm up the detector once using the first few frames of the first video.
    warmup_starts = list(range(0, min(4, len(first_image_files)), batch_size))
    command_queue.put((device, {'completed': 0, 'total': len(warmup_starts), 'description': 'Warm up'}))
    with torch.no_grad():
        for warmup_i, batch_start in enumerate(warmup_starts):
            batch_files = first_image_files[batch_start:batch_start + batch_size]
            warmup_images: list[polyis.dtypes.NPImage] = []
            for image_file in batch_files:
                frame = cv2.imread(os.path.join(first_compressed_frames_dir, image_file))
                assert frame is not None
                assert polyis.dtypes.is_np_image(frame)
                warmup_images.append(frame)
            polyis.models.detector.detect_batch(warmup_images, detector)
            command_queue.put((device, {'completed': warmup_i + 1, 'total': len(warmup_starts), 'description': 'Warm up'}))
        torch.cuda.synchronize()

    # Report initial progress: 0 of N videos done.
    command_queue.put((device, {'completed': 0, 'total': len(videos), 'description': description}))
    # Iterate over all videos in the split for this parameter combination.
    for i, video in enumerate(videos):
        detect_objects(dataset, video, classifier, tilesize, sample_rate,
                       tilepadding, canvas_scale, tracker, tracking_accuracy_threshold,
                       batch_size, detector)
        # Advance the progress bar by one unit after each video completes.
        command_queue.put((device, {'completed': i + 1, 'total': len(videos), 'description': description}))


def main(args):
    """
    Main function that orchestrates the object detection process on compressed images using parallel processing.

    This function serves as the entry point for the script. It:
    1. Validates the dataset directories exist
    2. Creates a list of all video/classifier/tilesize combinations to process
    3. Uses multiprocessing to process tasks in parallel across available GPUs
    4. Processes each video and saves detection results

    Args:
        args (argparse.Namespace): Parsed command line arguments containing:
            - clear (bool): Whether to remove and recreate the 040_compressed_detections folder for each video

    Note:
        - The script expects compressed images from 030_exec_compress.py in:
          {CACHE_DIR}/{dataset}/execution/{video_file}/033_compressed_frames/{classifier}_{tilesize}_{sample_rate}_{tilepadding}_s{scale_percent}/images/
        - Detection results are saved to:
          {CACHE_DIR}/{dataset}/execution/{video_file}/040_compressed_detections/{classifier}_{tilesize}_{sample_rate}_{tilepadding}_s{scale_percent}/detections.jsonl
        - Each line in the output JSONL file contains one bounding box [x1, y1, x2, y2]
        - When tilesize is 'all', all available tile sizes are processed
        - When classifiers is not specified, all classifiers in CLASSIFIERS_TO_TEST + ['Perfect'] are processed
        - If no compressed images are found for a video/tilesize/classifier combination, that combination is skipped
        - The number of processes equals the number of available GPUs
    """
    mp.set_start_method('spawn', force=True)

    # Determine which videosets to process based on arguments.
    selected_videosets = []
    if args.test:
        selected_videosets.append('test')
    if args.valid:
        selected_videosets.append('valid')
    # Default to valid only when no flags are provided.
    if not selected_videosets:
        selected_videosets = ['valid']

    # Build allowed-combo set for the test pass (None means no filtering applies).
    allowed_combos = build_pareto_combo_filter(
        DATASETS, selected_videosets,
        ['classifier', 'tilesize', 'sample_rate', 'tilepadding', 'canvas_scale',
         'tracker', 'tracking_accuracy_threshold'],
        collapse_tracker_when_no_threshold=True,
    )

    # Create tasks list with all video/classifier/tilesize combinations
    funcs: list[Callable[[int, mp.Queue], None]] = []

    if args.clear:
        print(f"Cleared existing 040_compressed_detections folder")
        for dataset in DATASETS:
            # Use selected videosets so --clear respects the current pass scope.
            for videoset in selected_videosets:
                videoset_dir = store.dataset(dataset, videoset)
                if not os.path.exists(videoset_dir):
                    continue
                videos = [f for f in os.listdir(videoset_dir) if f.endswith(('.mp4', '.avi', '.mov', '.mkv'))]
                for video in sorted(videos):
                    compressed_detections_dir = cache.exec(dataset, 'comp-dets', video)
                    if os.path.exists(compressed_detections_dir):
                        shutil.rmtree(compressed_detections_dir)

    for dataset, videoset in itertools.product(DATASETS, selected_videosets):
        videoset_dir = store.dataset(dataset, videoset)
        assert os.path.exists(videoset_dir), f"Videoset directory {videoset_dir} does not exist"

        videos = [f for f in os.listdir(videoset_dir) if f.endswith(('.mp4', '.avi', '.mov', '.mkv'))]
        for video in videos:
            shutil.rmtree(cache.exec(dataset, 'comp-dets', video), ignore_errors=True)
        for classifier, tilesize, tilepadding, sample_rate, canvas_scale, threshold in itertools.product(
            CLASSIFIERS, TILE_SIZES, TILEPADDING_MODES, SAMPLE_RATES, CANVAS_SCALES, TRACKING_ACCURACY_THRESHOLDS):
            for tracker in [None] if threshold is None else TRACKERS:
                # Skip parameter combos not on the Pareto front during the test pass.
                combo = (classifier, tilesize, sample_rate, tilepadding, canvas_scale, tracker, threshold)
                if allowed_combos is not None and combo not in allowed_combos[dataset]:
                    continue
                funcs.append(partial(detect_all, dataset, sorted(videos), classifier, tilesize, sample_rate,
                                     tilepadding, canvas_scale, tracker, threshold, args.batch_size))

    print(f"Created {len(funcs)} tasks to process")

    # Set up multiprocessing with ProgressBar
    # Use number of available GPUs as the number of processes
    num_gpus = torch.cuda.device_count()
    assert num_gpus > 0, "No GPUs available"
    print(f"Using {num_gpus} GPUs for parallel processing")

    if len(funcs) < num_gpus:
        num_gpus = len(funcs)

    ProgressBar(num_workers=num_gpus, num_tasks=len(funcs), refresh_per_second=10).run_all(funcs)
    print("All tasks completed!")


if __name__ == '__main__':
    main(parse_args())
