#!/usr/local/bin/python

import argparse
import itertools
import json
import os
import shutil
import time
import cv2
import torch.multiprocessing as mp
import queue
import threading
from functools import partial
from typing import Callable
import numpy as np
import torch

import polyis.models.detector
import polyis.dtypes
from polyis.utilities import TilePadding, format_time, ProgressBar, get_config, build_param_str
from polyis.io import cache, store
from polyis.pareto import build_pareto_combo_filter


config = get_config()
CLASSIFIERS: list[str] = config['EXEC']['CLASSIFIERS']
TILE_SIZES: list[int] = config['EXEC']['TILE_SIZES']
DATASETS: list[str] = config['EXEC']['DATASETS']
SAMPLE_RATES: list[int] = config['EXEC']['SAMPLE_RATES']
TILEPADDING_MODES: list[TilePadding] = config['EXEC']['TILEPADDING_MODES']
CANVAS_SCALES: list[float] = config['EXEC']['CANVAS_SCALE']
TRACKERS: list[str] = config['EXEC']['TRACKERS']
TRACKING_ACCURACY_THRESHOLDS: list[float] = config['EXEC']['TRACKING_ACCURACY_THRESHOLDS']
RELEVANCE_THRESHOLDS: list[float] = config['EXEC']['RELEVANCE_THRESHOLDS']


def parse_args():
    parser = argparse.ArgumentParser(description='Detect objects from packed images generated by 030_exec_pack.py')
    parser.add_argument('--clear', action='store_true',
                        help='Remove and recreate the 040_compressed_detections folder for each video')
    parser.add_argument('--batch_size', type=int, default=4,
                        help='Batch size for detection processing (default: 4)')
    parser.add_argument('--test', action='store_true')
    parser.add_argument('--valid', action='store_true')
    return parser.parse_args()


def detect_worker_thread(dataset: str, batch_queue: queue.Queue, result_queue: queue.Queue,
                         first_video_num_images: int, batch_size: int, gpu_id: int, stream: torch.cuda.Stream):
    """
    Worker thread for detecting objects in compressed images using auto-selected detector with CUDA streams.

    Each thread uses its own CUDA stream to enable true parallel execution on the GPU.
    The stream ensures that operations from different threads don't block each other.
    All GPU operations (data transfer and inference) happen within the stream context,
    and data transfers use non_blocking=True to allow overlap with computation.

    Args:
        dataset (str): Name of the dataset (used to auto-select detector)
        batch_queue (queue.Queue): Queue containing batches of (video, batch_start, batch_images) to process
        result_queue (queue.Queue): Queue to send results back (video, batch_start, batch_output)
        first_video_num_images (int): Number of images in the first video (used as hint for get_detector)
        batch_size (int): Batch size for detection processing
        gpu_id (int): GPU ID to use for processing
        stream (torch.cuda.Stream): CUDA stream for this thread's operations
    """
    # Set the current device for this thread
    torch.cuda.set_device(gpu_id)

    # Get detector instance for this thread
    detector = polyis.models.detector.get_detector(dataset, gpu_id, batch_size, first_video_num_images)

    with torch.no_grad(), torch.inference_mode():
        # Process batches from the queue until a None sentinel is received
        while True:
            batch_data = batch_queue.get(block=True)
            if batch_data is None:
                break

            # Unpack video identifier along with batch data
            video, batch_start, batch_images = batch_data

            # Run detection within the stream context for true parallelism
            # All PyTorch operations (including data transfers and model inference) will
            # be queued to this specific stream, allowing parallel execution with other streams
            with torch.cuda.stream(stream):
                # Run detection on the batch of images (already numpy arrays)
                # The detect_batch function will handle device placement, and since we're
                # in a stream context, PyTorch operations will use this stream
                batch_output = polyis.models.detector.detect_batch(batch_images, detector)

            # Send results back to main thread with video identifier
            result_queue.put((video, batch_start, batch_output))


def detect_parallel(dataset: str, videos: list[str], classifier: str, tilesize: int,
                    sample_rate: int, tilepadding: TilePadding, canvas_scale: float,
                    tracker: str | None, tracking_accuracy_threshold: float | None,
                    relevance_threshold: float,
                    batch_size: int, gpu_id: int, command_queue: mp.Queue):
    """
    Detect objects in compressed images using auto-selected detector with CUDA streams for true parallelism.

    Uses threading with CUDA streams to enable parallel execution of multiple detection operations
    on the same GPU without blocking each other. Processes multiple videos sequentially through
    the parallel pipeline, keeping worker threads alive across all videos.

    Args:
        dataset (str): Name of the dataset (used to auto-select detector)
        videos (list[str]): List of video filenames to process
        classifier (str): Classifier name used for compression
        tilesize (int): Tile size used for compression
        tilepadding (TilePadding): Whether padding was applied to classification results
        sample_rate (int): Sample rate for frame sampling
        canvas_scale (float): Canvas scale used for compression outputs
        tracker (str): Tracker name for upstream pruning
        tracking_accuracy_threshold (float | None): Accuracy threshold for pruning (None = no pruning)
        batch_size (int): Batch size for detection processing
        gpu_id (int): GPU ID to use for processing
        command_queue (mp.Queue): Queue for reporting progress to the main process
    """
    device = f'cuda:{gpu_id}'

    # Enable cuDNN benchmarking for optimal performance
    torch.backends.cudnn.benchmark = True

    param_str = build_param_str(classifier=classifier, tilesize=tilesize, sample_rate=sample_rate, tilepadding=tilepadding, canvas_scale=canvas_scale, tracker=tracker, tracking_accuracy_threshold=tracking_accuracy_threshold, relevance_threshold=relevance_threshold)
    description = f"{dataset} {param_str}"

    # Look up first video's image count as a representative hint for get_detector
    first_compressed_frames_dir = cache.exec(dataset, 'comp-frames', videos[0], param_str, 'images')
    first_image_files = sorted(f for f in os.listdir(first_compressed_frames_dir) if f.endswith('.jpg'))
    first_video_num_images = len(first_image_files)

    num_threads = 2

    # Use thread-safe queues for inter-thread communication
    batch_queue = queue.Queue()
    result_queue = queue.Queue()

    # Set device for main thread
    torch.cuda.set_device(gpu_id)

    # Create unique CUDA streams for each worker thread
    # Each stream allows independent parallel execution on the GPU
    streams = [torch.cuda.Stream(device=gpu_id) for _ in range(num_threads)]

    # Start worker threads (once for all videos)
    # Each thread uses its own CUDA stream to enable true parallelism
    threads = []
    for i in range(num_threads):
        thread = threading.Thread(target=detect_worker_thread,
                                   args=(dataset, batch_queue, result_queue,
                                         first_video_num_images, batch_size, gpu_id, streams[i]))
        threads.append(thread)
        thread.start()

    # Warmup phase: queue first few frames of first video through workers
    warmup_frames: list[np.ndarray] = []
    for image_file in first_image_files[:min(4, first_video_num_images)]:
        frame = cv2.imread(os.path.join(first_compressed_frames_dir, image_file))
        assert frame is not None
        assert polyis.dtypes.is_np_image(frame)
        warmup_frames.append(frame)
    # Queue warmup batches with a special video identifier
    warmup_num_batches = (len(warmup_frames) + batch_size - 1) // batch_size
    command_queue.put((device, {'completed': 0, 'total': warmup_num_batches, 'description': 'Warm up'}))
    for i in range(warmup_num_batches):
        batch_start = i * batch_size
        batch_images = warmup_frames[batch_start:batch_start + batch_size]
        batch_queue.put(('__warmup__', batch_start, batch_images))
    # Collect warmup results (discard them)
    for i in range(warmup_num_batches):
        result_queue.get(block=True)
        command_queue.put((device, {'completed': i + 1, 'total': warmup_num_batches, 'description': 'Warm up'}))
    # Synchronize all streams after warmup
    for stream in streams:
        stream.synchronize()
    torch.cuda.synchronize()

    # Report initial progress: 0 of N videos done
    command_queue.put((device, {'completed': 0, 'total': len(videos), 'description': description}))

    # Process each video sequentially through the parallel pipeline
    for video_idx, video in enumerate(videos):
        # Resolve compressed frames directory for this video
        compressed_frames_dir = cache.exec(dataset, 'comp-frames', video, param_str, 'images')
        assert os.path.exists(compressed_frames_dir), \
            f"Compressed frames directory {compressed_frames_dir} does not exist"

        # Create output directory for detections (clean slate)
        detections_output_dir = cache.exec(dataset, 'comp-dets', video, param_str)
        if os.path.exists(detections_output_dir):
            shutil.rmtree(detections_output_dir)
        os.makedirs(detections_output_dir, exist_ok=True)

        # Get all compressed image files for this video
        image_files = sorted(f for f in os.listdir(compressed_frames_dir) if f.endswith('.jpg'))

        # Read all frames for this video in the main thread
        frames: list[np.ndarray] = []
        for image_file in image_files:
            image_path = os.path.join(compressed_frames_dir, image_file)
            frame = cv2.imread(image_path)
            assert frame is not None
            assert polyis.dtypes.is_np_image(frame)
            frames.append(frame)

        # Queue all batches for this video
        num_batches = (len(image_files) + batch_size - 1) // batch_size
        start_time = (time.time_ns() / 1e6)
        for i in range(num_batches):
            batch_start = i * batch_size
            batch_images = frames[batch_start:batch_start + batch_size]
            batch_queue.put((video, batch_start, batch_images))

        # Collect all results for this video
        # Results may arrive out of order, so we collect them all first
        results_dict: dict[int, polyis.dtypes.DetArray] = {}
        completed_batches = 0
        while completed_batches < num_batches:
            result_video, batch_start, batch_output = result_queue.get(block=True)
            assert result_video == video, \
                f"Expected results for {video} but got {result_video}"
            # Store results by frame index within this video
            for i, detection in enumerate(batch_output):
                results_dict[batch_start + i] = detection
            completed_batches += 1

        # Synchronize all streams to ensure all GPU work is complete for this video
        for stream in streams:
            stream.synchronize()
        torch.cuda.synchronize()
        end_time = (time.time_ns() / 1e6)

        # Write results in order for this video
        with (open(os.path.join(detections_output_dir, 'detections.jsonl'), 'w') as f,
              open(os.path.join(detections_output_dir, 'runtimes.jsonl'), 'w') as fr):
            for i in range(len(image_files)):
                output_detection = results_dict[i]
                assert output_detection is not None
                f.write(json.dumps({ 'image_file': image_files[i], 'bboxes': output_detection.tolist() }) + '\n')
                fr.write(json.dumps(format_time(detect=(end_time - start_time) / len(image_files))) + '\n')

        # Advance the progress bar after each video completes
        command_queue.put((device, {'completed': video_idx + 1, 'total': len(videos), 'description': description}))

    # Signal worker threads to stop
    for i in range(num_threads):
        batch_queue.put(None)

    # Wait for all threads to finish
    for thread in threads:
        thread.join()

    # Final synchronization
    for stream in streams:
        stream.synchronize()
    torch.cuda.synchronize()


def detect_objects(dataset: str, video: str, classifier: str, tilesize: int,
                   sample_rate: int, tilepadding: TilePadding, canvas_scale: float,
                   tracker: str | None, tracking_accuracy_threshold: float | None,
                   relevance_threshold: float,
                   batch_size: int, detector):
    """
    Detect objects in compressed images using a pre-initialized detector.

    Args:
        dataset_name (str): Name of the dataset (used to auto-select detector)
        video (str): Name of the video file
        classifier (str): Classifier name used for compression
        tilesize (int): Tile size used for compression
        tilepadding (TilePadding): Whether padding was applied to classification results
        sample_rate (int): Sample rate for frame sampling
        canvas_scale (float): Canvas scale used for compression outputs
        tracker (str): Tracker name for upstream pruning
        tracking_accuracy_threshold (float | None): Accuracy threshold for pruning (None = no pruning)
        detector: Pre-initialized detector instance shared across all videos in this parameter combo
    """
    param_str = build_param_str(classifier=classifier, tilesize=tilesize, sample_rate=sample_rate, tilepadding=tilepadding, canvas_scale=canvas_scale, tracker=tracker, tracking_accuracy_threshold=tracking_accuracy_threshold, relevance_threshold=relevance_threshold)

    compressed_frames_dir = cache.exec(dataset, 'comp-frames', video, param_str, 'images')
    assert os.path.exists(compressed_frames_dir), \
        f"Compressed frames directory {compressed_frames_dir} does not exist"

    # Create output directory for detections
    detections_output_dir = cache.exec(dataset, 'comp-dets', video, param_str)
    if os.path.exists(detections_output_dir):
        # Remove the entire directory
        shutil.rmtree(detections_output_dir)
    os.makedirs(detections_output_dir, exist_ok=True)

    # Get all compressed image files
    image_files = [f for f in os.listdir(compressed_frames_dir) if f.endswith('.jpg')]

    with (open(os.path.join(detections_output_dir, 'detections.jsonl'), 'w') as f,
          open(os.path.join(detections_output_dir, 'runtimes.jsonl'), 'w') as fr,
          torch.no_grad()):
        # Process images in batches
        for batch_start in range(0, len(image_files), batch_size):
            batch_end = min(batch_start + batch_size, len(image_files))
            batch_files = image_files[batch_start:batch_end]

            # Read all images in the batch
            batch_images: list[polyis.dtypes.NPImage] = []
            batch_runtimes: list[dict] = []
            start_time = (time.time_ns() / 1e6)
            for image_file in batch_files:
                image_path = os.path.join(compressed_frames_dir, image_file)
                frame = cv2.imread(image_path)
                assert frame is not None
                assert polyis.dtypes.is_np_image(frame)
                batch_images.append(frame)
                batch_runtimes.append({'image_file': image_file})
            end_time = (time.time_ns() / 1e6)
            read_time_per_image = (end_time - start_time) / len(batch_files)

            # Detect objects in the batch
            start_time = (time.time_ns() / 1e6)
            batch_outputs = polyis.models.detector.detect_batch(batch_images, detector)
            end_time = (time.time_ns() / 1e6)
            detect_time_per_image = (end_time - start_time) / len(batch_files)

            # Process results for each image in the batch
            for idx, (image_file, outputs) in enumerate(zip(batch_files, batch_outputs)):
                runtime = batch_runtimes[idx]
                runtime['read'] = read_time_per_image
                runtime['detect'] = detect_time_per_image

                # Extract bounding boxes (x1, y1, x2, y2, score, ...) format
                bounding_boxes = outputs.tolist()

                # Save detection results
                f.write(json.dumps({ 'image_file': image_file, 'bboxes': bounding_boxes }) + '\n')
                fr.write(json.dumps(format_time(**runtime)) + '\n')


def detect_all(dataset: str, videos: list[str], classifier: str, tilesize: int,
               sample_rate: int, tilepadding: TilePadding, canvas_scale: float,
               tracker: str | None, tracking_accuracy_threshold: float | None,
               relevance_threshold: float,
               batch_size: int, gpu_id: int, command_queue: mp.Queue):
    device = f'cuda:{gpu_id}'
    # Build a human-readable description for the progress bar.
    param_str = build_param_str(classifier=classifier, tilesize=tilesize, sample_rate=sample_rate,
                                tilepadding=tilepadding, canvas_scale=canvas_scale, tracker=tracker,
                                tracking_accuracy_threshold=tracking_accuracy_threshold,
                                relevance_threshold=relevance_threshold)
    description = f"{dataset} {param_str}"

    # Initialize the detector once for all videos in this parameter combination.
    # Use the first video's image count as a representative batch-size hint.
    first_compressed_frames_dir = cache.exec(dataset, 'comp-frames', videos[0], param_str, 'images')
    first_image_files = sorted(f for f in os.listdir(first_compressed_frames_dir) if f.endswith('.jpg'))
    detector = polyis.models.detector.get_detector(dataset, gpu_id, batch_size, len(first_image_files))

    # Warm up the detector once using the first few frames of the first video.
    warmup_starts = list(range(0, min(4, len(first_image_files)), batch_size))
    command_queue.put((device, {'completed': 0, 'total': len(warmup_starts), 'description': 'Warm up'}))
    with torch.no_grad():
        for warmup_i, batch_start in enumerate(warmup_starts):
            batch_files = first_image_files[batch_start:batch_start + batch_size]
            warmup_images: list[polyis.dtypes.NPImage] = []
            for image_file in batch_files:
                frame = cv2.imread(os.path.join(first_compressed_frames_dir, image_file))
                assert frame is not None
                assert polyis.dtypes.is_np_image(frame)
                warmup_images.append(frame)
            polyis.models.detector.detect_batch(warmup_images, detector)
            command_queue.put((device, {'completed': warmup_i + 1, 'total': len(warmup_starts), 'description': 'Warm up'}))
        torch.cuda.synchronize()

    # Report initial progress: 0 of N videos done.
    command_queue.put((device, {'completed': 0, 'total': len(videos), 'description': description}))
    # Iterate over all videos in the split for this parameter combination.
    for i, video in enumerate(videos):
        detect_objects(dataset, video, classifier, tilesize, sample_rate,
                       tilepadding, canvas_scale, tracker, tracking_accuracy_threshold,
                       relevance_threshold,
                       batch_size, detector)
        # Advance the progress bar by one unit after each video completes.
        command_queue.put((device, {'completed': i + 1, 'total': len(videos), 'description': description}))


def main(args):
    """
    Main function that orchestrates the object detection process on compressed images using parallel processing.

    This function serves as the entry point for the script. It:
    1. Validates the dataset directories exist
    2. Creates a list of all video/classifier/tilesize combinations to process
    3. Uses multiprocessing to process tasks in parallel across available GPUs
    4. Processes each video and saves detection results

    Args:
        args (argparse.Namespace): Parsed command line arguments containing:
            - clear (bool): Whether to remove and recreate the 040_compressed_detections folder for each video

    Note:
        - The script expects compressed images from 030_exec_compress.py in:
          {CACHE_DIR}/{dataset}/execution/{video_file}/033_compressed_frames/{classifier}_{tilesize}_{sample_rate}_{tilepadding}_s{scale_percent}/images/
        - Detection results are saved to:
          {CACHE_DIR}/{dataset}/execution/{video_file}/040_compressed_detections/{classifier}_{tilesize}_{sample_rate}_{tilepadding}_s{scale_percent}/detections.jsonl
        - Each line in the output JSONL file contains one bounding box [x1, y1, x2, y2]
        - When tilesize is 'all', all available tile sizes are processed
        - When classifiers is not specified, all classifiers in CLASSIFIERS_TO_TEST + ['Perfect'] are processed
        - If no compressed images are found for a video/tilesize/classifier combination, that combination is skipped
        - The number of processes equals the number of available GPUs
    """
    mp.set_start_method('spawn', force=True)

    # Determine which videosets to process based on arguments.
    selected_videosets = []
    if args.test:
        selected_videosets.append('test')
    if args.valid:
        selected_videosets.append('valid')
    # Default to valid only when no flags are provided.
    if not selected_videosets:
        selected_videosets = ['valid']

    # Build allowed-combo set for the test pass (None means no filtering applies).
    allowed_combos = build_pareto_combo_filter(
        DATASETS, selected_videosets,
        ['classifier', 'tilesize', 'sample_rate', 'tilepadding', 'canvas_scale',
         'tracker', 'tracking_accuracy_threshold', 'relevance_threshold'],
        collapse_tracker_when_no_threshold=True,
    )

    # Create tasks list with all video/classifier/tilesize combinations
    funcs: list[Callable[[int, mp.Queue], None]] = []

    if args.clear:
        print(f"Cleared existing 040_compressed_detections folder")
        for dataset in DATASETS:
            # Use selected videosets so --clear respects the current pass scope.
            for videoset in selected_videosets:
                videoset_dir = store.dataset(dataset, videoset)
                if not os.path.exists(videoset_dir):
                    continue
                videos = [f for f in os.listdir(videoset_dir) if f.endswith(('.mp4', '.avi', '.mov', '.mkv'))]
                for video in sorted(videos):
                    compressed_detections_dir = cache.exec(dataset, 'comp-dets', video)
                    if os.path.exists(compressed_detections_dir):
                        shutil.rmtree(compressed_detections_dir)

    for dataset, videoset in itertools.product(DATASETS, selected_videosets):
        videoset_dir = store.dataset(dataset, videoset)
        assert os.path.exists(videoset_dir), f"Videoset directory {videoset_dir} does not exist"

        videos = [f for f in os.listdir(videoset_dir) if f.endswith(('.mp4', '.avi', '.mov', '.mkv'))]
        for video in videos:
            shutil.rmtree(cache.exec(dataset, 'comp-dets', video), ignore_errors=True)
        for classifier, tilesize, tilepadding, sample_rate, canvas_scale, acc_threshold, relevance_threshold in itertools.product(
            CLASSIFIERS, TILE_SIZES, TILEPADDING_MODES, SAMPLE_RATES, CANVAS_SCALES, TRACKING_ACCURACY_THRESHOLDS, RELEVANCE_THRESHOLDS):
            for tracker in [None] if acc_threshold is None else TRACKERS:
                # Skip parameter combos not on the Pareto front during the test pass.
                combo = (classifier, tilesize, sample_rate, tilepadding, canvas_scale, tracker, acc_threshold, relevance_threshold)
                if allowed_combos is not None and combo not in allowed_combos[dataset]:
                    continue
                funcs.append(partial(detect_all, dataset, sorted(videos), classifier, tilesize, sample_rate,
                                     tilepadding, canvas_scale, tracker, acc_threshold, relevance_threshold, args.batch_size))

    print(f"Created {len(funcs)} tasks to process")

    # Set up multiprocessing with ProgressBar
    # Use number of available GPUs as the number of processes
    num_gpus = torch.cuda.device_count()
    assert num_gpus > 0, "No GPUs available"
    print(f"Using {num_gpus} GPUs for parallel processing")

    if len(funcs) < num_gpus:
        num_gpus = len(funcs)

    ProgressBar(num_workers=num_gpus, num_tasks=len(funcs), refresh_per_second=10).run_all(funcs)
    print("All tasks completed!")


if __name__ == '__main__':
    main(parse_args())
