#!/usr/local/bin/python
"""
Convert tracking results to CVAT or MOT format.

This script reads tracking.jsonl files generated by p003_preprocess_groundtruth_tracking.py
and converts them to either CVAT XML or MOT 1.1 format for import into CVAT or other
tracking visualization/evaluation tools.

Input format (tracking.jsonl):
    Each line contains:
    {
        "frame_idx": <int>,
        "tracks": [[track_id, x1, y1, x2, y2], ...]
    }

Output formats:

1. MOT 1.1 (default, simpler):
    Text file with one detection per line:
    <frame>,<id>,<bb_left>,<bb_top>,<bb_width>,<bb_height>,<conf>,<x>,<y>,<z>
    - frame: 1-indexed frame number
    - id: track ID
    - bb_left, bb_top: top-left corner coordinates
    - bb_width, bb_height: bounding box dimensions
    - conf: confidence score (1.0 for ground truth)
    - x, y, z: 3D coordinates (-1 for 2D tracking)

2. CVAT XML:
    CVAT for video 1.1 XML format:
    - Contains metadata about the video (resolution, frame count, etc.)
    - Each track is represented as a <track> element with id and label
    - Each detection is a <box> element with frame number and bounding box coordinates

Usage:
    # Convert to MOT format (default)
    ./run preprocess/p008_preprocess_convert_tracking.py --test

    # Convert to CVAT XML format
    ./run preprocess/p008_preprocess_convert_tracking.py --test --format cvat

    # Convert from different source directory
    ./run preprocess/p008_preprocess_convert_tracking.py --test --source 002_naive

    # Convert all videosets
    ./run preprocess/p008_preprocess_convert_tracking.py --test --train --valid

Import into CVAT:
    - MOT 1.1: Project > Import annotations > MOT 1.1 > Select gt.txt
    - CVAT XML: Project > Import annotations > CVAT for video 1.1 > Select annotations.xml
"""

import argparse
import json
import os
from datetime import datetime
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom
from functools import partial
import multiprocessing as mp

from polyis.io import cache, store
from polyis.utilities import get_video_resolution, get_video_frame_count, ProgressBar, get_config


CONFIG = get_config()
EXEC_DATASETS = CONFIG['EXEC']['DATASETS']
EXEC_DIR_TO_STAGE = {v: k for k, v in cache.EXEC_STAGE_MAP.items()}


def parse_args():
    parser = argparse.ArgumentParser(description='Convert tracking results to CVAT or MOT format')
    parser.add_argument('--test', action='store_true', help='Process test videoset')
    parser.add_argument('--train', action='store_true', help='Process train videoset')
    parser.add_argument('--valid', action='store_true', help='Process valid videoset')
    parser.add_argument('--source', type=str, default='003_groundtruth', help='Source tracking directory (default: 003_groundtruth)')
    parser.add_argument('--format', type=str, default='mot', choices=['mot', 'cvat'], help='Output format: mot (default) or cvat')
    return parser.parse_args()


def load_tracking_results(tracking_path: str) -> dict[int, list[list[float]]]:
    """
    Load tracking results from JSONL file.

    Args:
        tracking_path (str): Path to tracking.jsonl file

    Returns:
        dict[int, list[list[float]]]: Frame tracks mapping frame_idx to list of [track_id, x1, y1, x2, y2]
    """
    # Check if file exists
    if not os.path.exists(tracking_path):
        return {}

    # Load tracking results from JSONL
    frame_tracks = {}
    with open(tracking_path, 'r') as f:
        for line in f:
            frame_data = json.loads(line.strip())
            frame_idx = frame_data['frame_idx']
            tracks = frame_data['tracks']
            frame_tracks[frame_idx] = tracks

    return frame_tracks


def create_cvat_xml(dataset: str, video_file: str, frame_tracks: dict[int, list[list[float]]],
                    width: int, height: int, num_frames: int) -> str:
    """
    Create CVAT XML annotation string from tracking results.

    Args:
        dataset (str): Dataset name
        video_file (str): Video filename
        frame_tracks (dict[int, list[list[float]]]): Frame tracks
        width (int): Video width
        height (int): Video height
        num_frames (int): Total number of frames

    Returns:
        str: CVAT XML string
    """
    # Create root element
    annotations = Element('annotations')

    # Add version
    version = SubElement(annotations, 'version')
    version.text = '1.1'

    # Add meta information
    meta = SubElement(annotations, 'meta')

    # Add task information
    task = SubElement(meta, 'task')

    # Task ID
    task_id = SubElement(task, 'id')
    task_id.text = '1'

    # Task name
    name = SubElement(task, 'name')
    name.text = f'{dataset}_{video_file}'

    # Task size (number of frames)
    size = SubElement(task, 'size')
    size.text = str(num_frames)

    # Task mode
    mode = SubElement(task, 'mode')
    mode.text = 'interpolation'

    # Overlap
    overlap = SubElement(task, 'overlap')
    overlap.text = '0'

    # Bugtracker
    bugtracker = SubElement(task, 'bugtracker')
    bugtracker.text = ''

    # Created and updated timestamps
    current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3] + '+00:00'
    created = SubElement(task, 'created')
    created.text = current_time
    updated = SubElement(task, 'updated')
    updated.text = current_time

    # Labels
    labels = SubElement(task, 'labels')
    label = SubElement(labels, 'label')
    label_name = SubElement(label, 'name')
    label_name.text = 'object'
    SubElement(label, 'attributes')

    # Segments
    segments = SubElement(task, 'segments')
    segment = SubElement(segments, 'segment')
    seg_id = SubElement(segment, 'id')
    seg_id.text = '1'
    start = SubElement(segment, 'start')
    start.text = '0'
    stop = SubElement(segment, 'stop')
    stop.text = str(num_frames - 1)
    url = SubElement(segment, 'url')
    url.text = video_file

    # Owner
    owner = SubElement(task, 'owner')
    username = SubElement(owner, 'username')
    username.text = 'converter'
    email = SubElement(owner, 'email')
    email.text = ''

    # Dumped timestamp
    dumped = SubElement(meta, 'dumped')
    dumped.text = current_time

    # Organize tracks by track_id
    # First, collect all detections for each track_id
    track_detections: dict[int, list[tuple[int, float, float, float, float]]] = {}

    # Iterate through all frames
    for frame_idx, tracks in frame_tracks.items():
        for track in tracks:
            # Track format: [track_id, x1, y1, x2, y2]
            track_id = int(track[0])
            x1, y1, x2, y2 = track[1], track[2], track[3], track[4]

            if track_id not in track_detections:
                track_detections[track_id] = []

            track_detections[track_id].append((frame_idx, x1, y1, x2, y2))

    # Sort track IDs for consistent output
    sorted_track_ids = sorted(track_detections.keys())

    # Create track elements
    for track_id in sorted_track_ids:
        detections = track_detections[track_id]

        # Sort detections by frame index
        detections.sort(key=lambda x: x[0])

        # Create track element
        track_elem = SubElement(annotations, 'track')
        track_elem.set('id', str(track_id))
        track_elem.set('label', 'object')

        # Add bounding boxes for each frame
        for frame_idx, x1, y1, x2, y2 in detections:
            box = SubElement(track_elem, 'box')
            box.set('frame', str(frame_idx))
            box.set('outside', '0')
            box.set('occluded', '0')
            box.set('keyframe', '1')
            # CVAT uses xtl, ytl (top-left) and xbr, ybr (bottom-right)
            box.set('xtl', f'{x1:.2f}')
            box.set('ytl', f'{y1:.2f}')
            box.set('xbr', f'{x2:.2f}')
            box.set('ybr', f'{y2:.2f}')

    # Convert to pretty-printed XML string
    xml_str = minidom.parseString(tostring(annotations, encoding='utf-8')).toprettyxml(indent='  ')

    return xml_str


def create_mot_format(frame_tracks: dict[int, list[list[float]]]) -> str:
    """
    Create MOT 1.1 format string from tracking results.

    MOT format: <frame>,<id>,<bb_left>,<bb_top>,<bb_width>,<bb_height>,<conf>,<x>,<y>,<z>
    - frame: 1-indexed (MOT convention)
    - id: track ID
    - bb_left, bb_top: top-left corner
    - bb_width, bb_height: bounding box dimensions
    - conf: confidence (1.0 for ground truth)
    - x, y, z: -1 (not used for 2D tracking)

    Args:
        frame_tracks (dict[int, list[list[float]]]): Frame tracks

    Returns:
        str: MOT format string
    """
    # Collect all detections and sort by frame and track ID
    lines = []

    # Get all frame indices and sort them
    frame_indices = sorted(frame_tracks.keys())

    # Process each frame
    for frame_idx in frame_indices:
        tracks = frame_tracks[frame_idx]

        # Sort tracks by track ID for consistent output
        sorted_tracks = sorted(tracks, key=lambda x: int(x[0]))

        for track in sorted_tracks:
            # Track format: [track_id, x1, y1, x2, y2]
            track_id = int(track[0])
            x1, y1, x2, y2 = track[1], track[2], track[3], track[4]

            # Convert to MOT format
            # MOT uses 1-indexed frames (add 1 to 0-indexed frame_idx)
            mot_frame = frame_idx + 1
            # Calculate width and height
            bb_width = x2 - x1
            bb_height = y2 - y1
            # MOT format line
            line = f"{mot_frame},{track_id},{x1:.2f},{y1:.2f},{bb_width:.2f},{bb_height:.2f},1.0,-1,-1,-1"
            lines.append(line)

    return '\n'.join(lines) + '\n'


def convert_video(dataset: str, video_file: str, source_dir: str, output_format: str = 'mot') -> None:
    """
    Convert tracking results for a single video to specified format.

    Args:
        dataset (str): Dataset name
        video_file (str): Video filename
        source_dir (str): Source tracking directory name (e.g., '003_groundtruth')
        output_format (str): Output format ('mot' or 'cvat')
    """
    # Load tracking results
    stage = EXEC_DIR_TO_STAGE[source_dir]
    tracking_path = cache.exec(dataset, stage, video_file, 'tracking.jsonl')
    frame_tracks = load_tracking_results(tracking_path)

    # Skip if no tracking results
    if not frame_tracks:
        print(f"No tracking results found for {dataset}/{video_file}")
        return

    # Create output directory
    output_dir = cache.exec(dataset, stage, video_file, output_format)
    os.makedirs(output_dir, exist_ok=True)

    if output_format == 'mot':
        # Create MOT format
        mot_content = create_mot_format(frame_tracks)

        # Save MOT file (standard filename is gt.txt for ground truth)
        output_path = os.path.join(output_dir, 'gt.txt')
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(mot_content)

        print(f"Converted {dataset}/{video_file} -> {output_path}")

    elif output_format == 'cvat':
        # Get video metadata for CVAT XML
        width, height = get_video_resolution(dataset, video_file)
        num_frames = get_video_frame_count(dataset, video_file)

        # Create CVAT XML
        cvat_xml = create_cvat_xml(dataset, video_file, frame_tracks, width, height, num_frames)

        # Save CVAT XML
        output_path = os.path.join(output_dir, 'annotations.xml')
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(cvat_xml)

        print(f"Converted {dataset}/{video_file} -> {output_path}")

    else:
        raise ValueError(f"Unsupported output format: {output_format}")


def main():
    """
    Main function that orchestrates the conversion process.

    This function:
    1. Processes multiple datasets based on command-line arguments
    2. For each dataset, finds all videos with tracking results
    3. Converts tracking.jsonl to specified format (MOT or CVAT XML)
    4. Saves the results in format-specific subdirectory

    Note:
        - Input: {CACHE_DIR}/{dataset}/execution/{video_file}/{source_dir}/tracking.jsonl
        - Output MOT: {CACHE_DIR}/{dataset}/execution/{video_file}/{source_dir}/mot/gt.txt
        - Output CVAT: {CACHE_DIR}/{dataset}/execution/{video_file}/{source_dir}/cvat/annotations.xml
    """
    args = parse_args()

    # Determine which videosets to process based on arguments
    splits = []
    if args.test:
        splits.append('test')
    if args.train:
        splits.append('train')
    if args.valid:
        splits.append('valid')

    # If no videosets are specified, default to test
    if not splits:
        splits = ['test']

    # Process each dataset
    for dataset in EXEC_DATASETS:
        dataset_dir = store.dataset(dataset)

        # Validate dataset directory
        if not os.path.exists(dataset_dir):
            print(f"Warning: Dataset directory {dataset_dir} does not exist, skipping...")
            continue

        # Get all video files from the dataset directory
        video_files: list[str] = []
        for videoset in splits:
            videoset_dir = store.dataset(dataset, videoset)
            if not os.path.exists(videoset_dir):
                print(f"Warning: Videoset directory {videoset_dir} does not exist, skipping...")
                continue

            # Find all video files
            for f in os.listdir(videoset_dir):
                if f.endswith(('.mp4', '.avi', '.mov', '.mkv')):
                    video_files.append(videoset + '/' + f)

        # Skip if no videos found
        if len(video_files) == 0:
            print(f"No video files found in {dataset_dir}")
            continue

        # Convert each video
        print(f"\nProcessing dataset: {dataset}")
        print(f"Found {len(video_files)} videos")
        print(f"Source directory: {args.source}")
        print(f"Output format: {args.format}")

        for video_file in video_files:
            video = video_file.split('/')[-1]
            convert_video(dataset, video, args.source, args.format)


if __name__ == '__main__':
    main()
